# This workflow builds and tests PRs

name: PR build & test

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'

jobs:
  build-n-publish:  
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: Install and upload if not up to date
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: |
        pip install --extra-index-url https://test.pypi.org/simple/ tuneit==$(python -m get_version setup.py) || (
          python setup.py sdist
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          count=0
          while ! pip install --extra-index-url https://test.pypi.org/simple/ tuneit==$(python -m get_version setup.py) && [ $count -lt 20 ]; do
            sleep 1
            count=$((count+1))
          done
        )

    - name: Run tests
      run: |
        pip install --extra-index-url https://test.pypi.org/simple/ tuneit[all]==$(python -m get_version setup.py)
        pip install pytest
        pip install pytest-cov
        pytest -v

